-- ============================================
-- Barangay Health Appointment System
-- Run this in Supabase SQL Editor
-- ============================================

CREATE TABLE IF NOT EXISTS patients (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    patient_name VARCHAR(100) NOT NULL,
    department VARCHAR(50) NOT NULL,
    concern TEXT,
    date DATE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);

INSERT INTO patients (patient_name, department, concern, date) VALUES
('Juan Dela Cruz', 'Medical', 'Fever and headache', '2026-05-01'),
('Maria Santos', 'Dental', 'Tooth extraction', '2026-05-02'),
('Jose Reyes', 'Vaccination', 'Pfizer booster dose', '2026-05-03'),
('Ana Garcia', 'Medical', 'High blood pressure check', '2026-05-04'),
('Pedro Bautista', 'Dental', 'Dental cleaning', '2026-05-05'),
('Rosa Mendoza', 'Vaccination', 'Flu vaccine', '2026-05-06'),
('Carlos Aquino', 'Medical', 'Diabetes follow-up', '2026-05-07'),
('Luz Villanueva', 'Dental', 'Cavity filling', '2026-05-08'),
('Ramon Castro', 'Vaccination', 'Hepatitis B vaccine', '2026-05-09'),
('Elena Torres', 'Medical', 'Cough and colds', '2026-05-10'),
('Miguel Flores', 'Dental', 'Tooth pain', '2026-05-11'),
('Cristina Ramos', 'Vaccination', 'COVID-19 booster', '2026-05-12');
